# Generated by Django 6.0 on 2025-12-26 03:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_one_product',
            field=models.ImageField(blank=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_three_product',
            field=models.ImageField(blank=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_two_product',
            field=models.ImageField(blank=True, upload_to='uploads/product/'),
        ),
    ]
