# Generated by Django 6.0 on 2025-12-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image_one_product',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_three_product',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image_two_product',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
