# Generated by Django 6.0 on 2026-02-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_profile_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('PROCESS', 'Process'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'order_audit',
                'db_table': 'order_audit',
            },
        ),
    ]
