# Generated by Django 6.0 on 2026-02-22 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderaudit_options_orderaudit_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
