# Generated by Django 6.0 on 2026-02-22 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
