# Generated by Django 6.0 on 2026-02-22 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_favorite_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
