# Generated by Django 6.0 on 2026-02-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_uid_orderaudit_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uid',
        ),
    ]
